### ISSUE TITLE
Using old beta annotations for arch and os

### ISSUE THREAD

**Issue by loopingz** [sysdiglabs/charts#1098]
The sysdig charts are using old annotations:

```
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[1].matchExpressions[0].key: beta.kubernetes.io/arch is deprecated since v1.14; use "kubernetes.io/arch" instead
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[1].matchExpressions[1].key: beta.kubernetes.io/os is deprecated since v1.14; use "kubernetes.io/os" instead
```

**Comment by loopingz** [comment]
This https://github.com/sysdiglabs/charts/blob/0df702c91806ece779215a2b1992d3ead6a7e7bc/charts/kspm-collector/templates/deployment.yaml#L42  and this
https://github.com/sysdiglabs/charts/blob/0df702c91806ece779215a2b1992d3ead6a7e7bc/charts/node-analyzer/values.yaml#L153 add both conditions to avoid having to filter based on Kubernetes version

**Comment by mavimo** [comment]
Thx @aroberts87 for the fix! 🙌 

@loopingz I'm going to close this issue!
