### ISSUE TITLE
cgroups v2 for sysdig agent

### ISSUE THREAD

**Issue by justin-chizer** [sysdiglabs/charts#1279]
- Please update the Sysdig agent to be compatible with AKS.
- Beginning with AKS 1.25 and the upgrade to Ubuntu Ubuntu 22.04.2 LTS the sysdig agent breaks our standard environment for deploying java apps because of the cgroup v2 setting
- This makes Sysdig Secure unusable for us.

@aroberts87

**Comment by dark-vex** [comment]
Hey @justin-chizer thanks for writing to us, I see that one of your colleague reached us via a support case for the same inquiry.

Sysdig Agent will support cgroup v2 starting from version 12.16.x. I don't have a precise ETA yet for when will be out but we are close to release this new agent version.

I proceed in closing this issue, this channel should be used only for issue related to the helm charts :-)

If you have any further question, please feel free to reach-out our support team via a support case:
https://docs.sysdig.com/en/docs/administration/get-help-using-sysdig-support/contact-support/
