### ISSUE TITLE
`cluster-scanner` must not set AMD64 `nodeSelector`

### ISSUE THREAD

**Issue by aquam8** [sysdiglabs/charts#1399]
Hi,

`cluster-scanner` appears to be ARM compatible but it has still the `nodeSelector` property set to be scheduled on AMD64 only.

Could this please be removed?

Thank you

**Comment by dark-vex** [comment]
Hi Matt,

thank you for your message, `cluster-scanner` image is not yet CA/GA this is why we still have `nodeSelector` property set.
Andrew (@andrewd-sysdig) is discussing this internally with engineering/product and he will reach you out.

Cheers,
Daniele
