### ISSUE TITLE
dnsPolicy not set for node-analyzer daemonset while hostNetworking set true

### ISSUE THREAD

**Issue by vipulagarwal** [sysdiglabs/charts#1631]
The `node-analyzer` daemonset sets `hostNetworking: true` but do not specify a `dnsPolicy`.

This results into `dnsPolicy` defaulting to `ClusterFirst`. It should be explicitly set to `ClusterFirstWithHostNet` as per the docs[1]

[1] https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

**Comment by mavimo** [comment]
@vipulagarwal thanks for your feedback!
