### ISSUE TITLE
Test resources are being rendered via helm

### ISSUE THREAD

**Issue by spodlesny-bloomreach** [sysdiglabs/charts#1640]
Hey, seems like test charts are being rendered in latest version even when they should be ignored by `.helmignore` file.

For example, [this](https://github.com/sysdiglabs/charts/blob/main/charts/agent/templates/tests/test-rollout.yaml) resource can be seen when running: `helm template sysdig-deploy --namespace sysdig-agent templates/platform/sysdig-agent/helm`

Can you fix it please? It's blocking us from updating to latest helm chart. 

Thanks :) 

Related ticket: 00026796

**Comment by AlbertoBarba** [comment]
Hi @spodlesny-bloomreach, did u try to run the template command adding the `--skip-tests` additional flag?

**Comment by spodlesny-bloomreach** [comment]
Yes, that fixed the issue. We must fix our release process to include this. 

Thank you. I would not think that test cases are rendered by default.
