### ISSUE TITLE
Cluster Scoped resource is installed in namespace.

### ISSUE THREAD

**Issue by mujtaba-ahmed12** [sysdiglabs/charts#1862]
Cluster scoped resource **ValidatingWebhookConfiguration** is being installed in namespace [here](https://github.com/sysdiglabs/charts/blob/main/charts/cluster-shield/templates/validatingwebhookconfiguration.yaml#L13). While Helm and K8S ignores the error and deploys the chart, [Google Config Sync ](https://cloud.google.com/kubernetes-engine/enterprise/config-sync/docs/reference/errors?_gl=1*118nxbu*_ga*MTk5Nzk1MzEzNi4xNjU0MjQ1MjM3*_ga_WH2QY8WWF5*MTcyMjM1MjM3MS4xOTAuMS4xNzIyMzUyNDEyLjAuMC4w#knv1052)has more strict validation and does not deploy resource at all.

**Comment by AlbertoBarba** [comment]
Hi @mujtaba-ahmed12, thanks for this feedback. We are going to release soon a new version of the chart to fix that

**Comment by AlbertoBarba** [comment]
@mujtaba-ahmed12 we just released version 1.2.0 of the chart that contains a fix for this.
Feel free to reopen this issue if you have any doubt.
